### ISSUE TITLE
Add a lint test checking for coverage of standardized variants

### ISSUE THREAD

**Issue by jamesgk** [googlei18n/nototools#12] opened 2015-06-09 23:29 UTC
From @roozbehp:

I just found that the Noto Sans Symbols misses the support for standardized 
variants (issue 321). Please add a test to noto_lint checking for the support.

The data table is at 
http://www.unicode.org/Public/8.0.0/ucd/StandardizedVariants-8.0.0d2.txt.

There are five classes:

1. Emoji/text variation sequences ending in FE0E/FE0F should be ignored for 
now. The glyphs will be in different fonts anyway.

2. CJK ones should be ignore for now, since noto_lint doesn't test the CJK 
fonts yet.

3. Noto Sans Mongolian and Noto Sans Phags-pa seem to support the standardized 
variant sequences through GSUB rules (they follow Microsoft's font, so it works 
with HarfBuzz), although I didn't manually check all cases. A test should be 
added to check that all the standardized sequences are supported in the fonts.

4. The symbol set is missing (and should probably be implemented in the font 
using cmap subtable format 14). A test should be added to check they exist in 
the font.

Moved from googlei18n/noto-fonts#322

**Comment by jamesgk** [comment] 2015-06-09 23:29
cc @behdad @jungshik

**Comment by dougfelt** [comment] 2015-10-28 00:11
@roozbeh, you mentioned Mongolian.  I've been developing a test for this, ran it on Mongolian, and there's one combination that doesn't seem to be supported:

Automatic testing for 'unhinted,NotoSansMongolian-Regular.ttf', Version 1.04 uh:
E <complex/gsub/variants> Expected GSUB to generate all standard variants, but 1 cases did not (182d 180b (fina): [u182D.fin=0+1358|space=0+0])

There's a web site https://r12a.github.io/scripts/mongolian/variants that seems to indicate that this might be intentional-- NotoSansMongolian is one of the fonts examined on the site.  I'm not sure how current the site is w.r.t. the version of StandardizedVariants.txt I'm using.  Do you know anything about this site?

**Comment by dougfelt** [comment] 2015-10-28 00:16
Btw, the output indicates that Harfbuzz generated two glyphs: 182D.fin and space, when asked to generate output for 182d 180b with features -isol,fin.  There's no ligature data in NotoSansMongolian for 182d 180b (there is for 182d 182c).  All other combinations generate a single glyph as output, so this correctly indicates that this is a mismatch with StandardizedVariants.txt.  The question is whether it is intentionally differing from StandardizedVariants, or adhering to an earlier version of StandardizedVariants, or what.

**Comment by dougfelt** [comment] 2015-10-29 18:24
Fixed in ec48d31c9349e61ca44998a8b9a70b0280a72351

The question of whether the Mongolian behavior is as intended is still open.  I'll file another bug for that.

**Closed by dougfelt** 2015-10-29 18:24 UTC
Labels: Android, bug
